name: build
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
            cache: 'npm' # ускоряет повторные сборки
            
        - name: Setup project
          run: make setup
        
        - name: Run tests
          run: make test

        - name: Run linter
          run: make lint
        
        - name: Print Hello from Hexlet
          uses: hexlet-components/hello-from-hexlet-action@release